/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-05-27 16:00:31 UTC)
 * on 2016-06-14 at 21:56:31 UTC 
 * Modify at your own risk.
 */

package com.appspot.trabalholp.gradeapi.model;

/**
 * Model definition for Nota.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the gradeapi. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Nota extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Avaliacao avaliacao;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String matriculaAluno;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float pontuacao;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String respostas;

  /**
   * @return value or {@code null} for none
   */
  public Avaliacao getAvaliacao() {
    return avaliacao;
  }

  /**
   * @param avaliacao avaliacao or {@code null} for none
   */
  public Nota setAvaliacao(Avaliacao avaliacao) {
    this.avaliacao = avaliacao;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Nota setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getMatriculaAluno() {
    return matriculaAluno;
  }

  /**
   * @param matriculaAluno matriculaAluno or {@code null} for none
   */
  public Nota setMatriculaAluno(java.lang.String matriculaAluno) {
    this.matriculaAluno = matriculaAluno;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getPontuacao() {
    return pontuacao;
  }

  /**
   * @param pontuacao pontuacao or {@code null} for none
   */
  public Nota setPontuacao(java.lang.Float pontuacao) {
    this.pontuacao = pontuacao;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getRespostas() {
    return respostas;
  }

  /**
   * @param respostas respostas or {@code null} for none
   */
  public Nota setRespostas(java.lang.String respostas) {
    this.respostas = respostas;
    return this;
  }

  @Override
  public Nota set(String fieldName, Object value) {
    return (Nota) super.set(fieldName, value);
  }

  @Override
  public Nota clone() {
    return (Nota) super.clone();
  }

}
