/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-05-27 16:00:31 UTC)
 * on 2016-06-14 at 23:57:12 UTC 
 * Modify at your own risk.
 */

package com.appspot.trabalholp_1342.gradeapi.model;

/**
 * Model definition for Avaliacao.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the gradeapi. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Avaliacao extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String disciplina;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String gabarito;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String matriculaProfessor;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nome;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean temFator;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float valor;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDisciplina() {
    return disciplina;
  }

  /**
   * @param disciplina disciplina or {@code null} for none
   */
  public Avaliacao setDisciplina(java.lang.String disciplina) {
    this.disciplina = disciplina;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getGabarito() {
    return gabarito;
  }

  /**
   * @param gabarito gabarito or {@code null} for none
   */
  public Avaliacao setGabarito(java.lang.String gabarito) {
    this.gabarito = gabarito;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Avaliacao setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getMatriculaProfessor() {
    return matriculaProfessor;
  }

  /**
   * @param matriculaProfessor matriculaProfessor or {@code null} for none
   */
  public Avaliacao setMatriculaProfessor(java.lang.String matriculaProfessor) {
    this.matriculaProfessor = matriculaProfessor;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNome() {
    return nome;
  }

  /**
   * @param nome nome or {@code null} for none
   */
  public Avaliacao setNome(java.lang.String nome) {
    this.nome = nome;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getTemFator() {
    return temFator;
  }

  /**
   * @param temFator temFator or {@code null} for none
   */
  public Avaliacao setTemFator(java.lang.Boolean temFator) {
    this.temFator = temFator;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getValor() {
    return valor;
  }

  /**
   * @param valor valor or {@code null} for none
   */
  public Avaliacao setValor(java.lang.Float valor) {
    this.valor = valor;
    return this;
  }

  @Override
  public Avaliacao set(String fieldName, Object value) {
    return (Avaliacao) super.set(fieldName, value);
  }

  @Override
  public Avaliacao clone() {
    return (Avaliacao) super.clone();
  }

}
