/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-05-27 16:00:31 UTC)
 * on 2016-06-14 at 21:56:31 UTC 
 * Modify at your own risk.
 */

package com.appspot.trabalholp.gradeapi;

/**
 * Service definition for Gradeapi (v1).
 *
 * <p>
 * API para gerenciar as notas e avaliacoes criadas
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link GradeapiRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Gradeapi extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.21.0 of the gradeapi library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://TrabalhoLP.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "gradeapi/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Gradeapi(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Gradeapi(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "addAvaliacao".
   *
   * This request holds the parameters needed by the gradeapi server.  After setting any optional
   * parameters, call the {@link AddAvaliacao#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.appspot.trabalholp.gradeapi.model.Avaliacao}
   * @return the request
   */
  public AddAvaliacao addAvaliacao(com.appspot.trabalholp.gradeapi.model.Avaliacao content) throws java.io.IOException {
    AddAvaliacao result = new AddAvaliacao(content);
    initialize(result);
    return result;
  }

  public class AddAvaliacao extends GradeapiRequest<com.appspot.trabalholp.gradeapi.model.Avaliacao> {

    private static final String REST_PATH = "salvaAvaliacao";

    /**
     * Create a request for the method "addAvaliacao".
     *
     * This request holds the parameters needed by the the gradeapi server.  After setting any
     * optional parameters, call the {@link AddAvaliacao#execute()} method to invoke the remote
     * operation. <p> {@link
     * AddAvaliacao#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.appspot.trabalholp.gradeapi.model.Avaliacao}
     * @since 1.13
     */
    protected AddAvaliacao(com.appspot.trabalholp.gradeapi.model.Avaliacao content) {
      super(Gradeapi.this, "POST", REST_PATH, content, com.appspot.trabalholp.gradeapi.model.Avaliacao.class);
    }

    @Override
    public AddAvaliacao setAlt(java.lang.String alt) {
      return (AddAvaliacao) super.setAlt(alt);
    }

    @Override
    public AddAvaliacao setFields(java.lang.String fields) {
      return (AddAvaliacao) super.setFields(fields);
    }

    @Override
    public AddAvaliacao setKey(java.lang.String key) {
      return (AddAvaliacao) super.setKey(key);
    }

    @Override
    public AddAvaliacao setOauthToken(java.lang.String oauthToken) {
      return (AddAvaliacao) super.setOauthToken(oauthToken);
    }

    @Override
    public AddAvaliacao setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (AddAvaliacao) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public AddAvaliacao setQuotaUser(java.lang.String quotaUser) {
      return (AddAvaliacao) super.setQuotaUser(quotaUser);
    }

    @Override
    public AddAvaliacao setUserIp(java.lang.String userIp) {
      return (AddAvaliacao) super.setUserIp(userIp);
    }

    @Override
    public AddAvaliacao set(String parameterName, Object value) {
      return (AddAvaliacao) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "addNota".
   *
   * This request holds the parameters needed by the gradeapi server.  After setting any optional
   * parameters, call the {@link AddNota#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.appspot.trabalholp.gradeapi.model.Nota}
   * @return the request
   */
  public AddNota addNota(com.appspot.trabalholp.gradeapi.model.Nota content) throws java.io.IOException {
    AddNota result = new AddNota(content);
    initialize(result);
    return result;
  }

  public class AddNota extends GradeapiRequest<com.appspot.trabalholp.gradeapi.model.Nota> {

    private static final String REST_PATH = "salvaNotas";

    /**
     * Create a request for the method "addNota".
     *
     * This request holds the parameters needed by the the gradeapi server.  After setting any
     * optional parameters, call the {@link AddNota#execute()} method to invoke the remote operation.
     * <p> {@link
     * AddNota#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.appspot.trabalholp.gradeapi.model.Nota}
     * @since 1.13
     */
    protected AddNota(com.appspot.trabalholp.gradeapi.model.Nota content) {
      super(Gradeapi.this, "POST", REST_PATH, content, com.appspot.trabalholp.gradeapi.model.Nota.class);
    }

    @Override
    public AddNota setAlt(java.lang.String alt) {
      return (AddNota) super.setAlt(alt);
    }

    @Override
    public AddNota setFields(java.lang.String fields) {
      return (AddNota) super.setFields(fields);
    }

    @Override
    public AddNota setKey(java.lang.String key) {
      return (AddNota) super.setKey(key);
    }

    @Override
    public AddNota setOauthToken(java.lang.String oauthToken) {
      return (AddNota) super.setOauthToken(oauthToken);
    }

    @Override
    public AddNota setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (AddNota) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public AddNota setQuotaUser(java.lang.String quotaUser) {
      return (AddNota) super.setQuotaUser(quotaUser);
    }

    @Override
    public AddNota setUserIp(java.lang.String userIp) {
      return (AddNota) super.setUserIp(userIp);
    }

    @Override
    public AddNota set(String parameterName, Object value) {
      return (AddNota) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listAvaliacoes".
   *
   * This request holds the parameters needed by the gradeapi server.  After setting any optional
   * parameters, call the {@link ListAvaliacoes#execute()} method to invoke the remote operation.
   *
   * @param matriculaProf
   * @return the request
   */
  public ListAvaliacoes listAvaliacoes(java.lang.String matriculaProf) throws java.io.IOException {
    ListAvaliacoes result = new ListAvaliacoes(matriculaProf);
    initialize(result);
    return result;
  }

  public class ListAvaliacoes extends GradeapiRequest<com.appspot.trabalholp.gradeapi.model.AvaliacaoCollection> {

    private static final String REST_PATH = "recuperaAvaliacoes/{matriculaProf}";

    /**
     * Create a request for the method "listAvaliacoes".
     *
     * This request holds the parameters needed by the the gradeapi server.  After setting any
     * optional parameters, call the {@link ListAvaliacoes#execute()} method to invoke the remote
     * operation. <p> {@link ListAvaliacoes#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param matriculaProf
     * @since 1.13
     */
    protected ListAvaliacoes(java.lang.String matriculaProf) {
      super(Gradeapi.this, "POST", REST_PATH, null, com.appspot.trabalholp.gradeapi.model.AvaliacaoCollection.class);
      this.matriculaProf = com.google.api.client.util.Preconditions.checkNotNull(matriculaProf, "Required parameter matriculaProf must be specified.");
    }

    @Override
    public ListAvaliacoes setAlt(java.lang.String alt) {
      return (ListAvaliacoes) super.setAlt(alt);
    }

    @Override
    public ListAvaliacoes setFields(java.lang.String fields) {
      return (ListAvaliacoes) super.setFields(fields);
    }

    @Override
    public ListAvaliacoes setKey(java.lang.String key) {
      return (ListAvaliacoes) super.setKey(key);
    }

    @Override
    public ListAvaliacoes setOauthToken(java.lang.String oauthToken) {
      return (ListAvaliacoes) super.setOauthToken(oauthToken);
    }

    @Override
    public ListAvaliacoes setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListAvaliacoes) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListAvaliacoes setQuotaUser(java.lang.String quotaUser) {
      return (ListAvaliacoes) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListAvaliacoes setUserIp(java.lang.String userIp) {
      return (ListAvaliacoes) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String matriculaProf;

    /**

     */
    public java.lang.String getMatriculaProf() {
      return matriculaProf;
    }

    public ListAvaliacoes setMatriculaProf(java.lang.String matriculaProf) {
      this.matriculaProf = matriculaProf;
      return this;
    }

    @Override
    public ListAvaliacoes set(String parameterName, Object value) {
      return (ListAvaliacoes) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listNotas".
   *
   * This request holds the parameters needed by the gradeapi server.  After setting any optional
   * parameters, call the {@link ListNotas#execute()} method to invoke the remote operation.
   *
   * @param matriculaAluno
   * @return the request
   */
  public ListNotas listNotas(java.lang.String matriculaAluno) throws java.io.IOException {
    ListNotas result = new ListNotas(matriculaAluno);
    initialize(result);
    return result;
  }

  public class ListNotas extends GradeapiRequest<com.appspot.trabalholp.gradeapi.model.NotaCollection> {

    private static final String REST_PATH = "recuperaNotas/{matriculaAluno}";

    /**
     * Create a request for the method "listNotas".
     *
     * This request holds the parameters needed by the the gradeapi server.  After setting any
     * optional parameters, call the {@link ListNotas#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListNotas#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param matriculaAluno
     * @since 1.13
     */
    protected ListNotas(java.lang.String matriculaAluno) {
      super(Gradeapi.this, "POST", REST_PATH, null, com.appspot.trabalholp.gradeapi.model.NotaCollection.class);
      this.matriculaAluno = com.google.api.client.util.Preconditions.checkNotNull(matriculaAluno, "Required parameter matriculaAluno must be specified.");
    }

    @Override
    public ListNotas setAlt(java.lang.String alt) {
      return (ListNotas) super.setAlt(alt);
    }

    @Override
    public ListNotas setFields(java.lang.String fields) {
      return (ListNotas) super.setFields(fields);
    }

    @Override
    public ListNotas setKey(java.lang.String key) {
      return (ListNotas) super.setKey(key);
    }

    @Override
    public ListNotas setOauthToken(java.lang.String oauthToken) {
      return (ListNotas) super.setOauthToken(oauthToken);
    }

    @Override
    public ListNotas setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListNotas) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListNotas setQuotaUser(java.lang.String quotaUser) {
      return (ListNotas) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListNotas setUserIp(java.lang.String userIp) {
      return (ListNotas) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String matriculaAluno;

    /**

     */
    public java.lang.String getMatriculaAluno() {
      return matriculaAluno;
    }

    public ListNotas setMatriculaAluno(java.lang.String matriculaAluno) {
      this.matriculaAluno = matriculaAluno;
      return this;
    }

    @Override
    public ListNotas set(String parameterName, Object value) {
      return (ListNotas) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listNotasPorProf".
   *
   * This request holds the parameters needed by the gradeapi server.  After setting any optional
   * parameters, call the {@link ListNotasPorProf#execute()} method to invoke the remote operation.
   *
   * @param matriculaProf
   * @return the request
   */
  public ListNotasPorProf listNotasPorProf(java.lang.String matriculaProf) throws java.io.IOException {
    ListNotasPorProf result = new ListNotasPorProf(matriculaProf);
    initialize(result);
    return result;
  }

  public class ListNotasPorProf extends GradeapiRequest<com.appspot.trabalholp.gradeapi.model.NotaCollection> {

    private static final String REST_PATH = "recuperaNotasPorProf/{matriculaProf}";

    /**
     * Create a request for the method "listNotasPorProf".
     *
     * This request holds the parameters needed by the the gradeapi server.  After setting any
     * optional parameters, call the {@link ListNotasPorProf#execute()} method to invoke the remote
     * operation. <p> {@link ListNotasPorProf#initialize(com.google.api.client.googleapis.services.Abs
     * tractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param matriculaProf
     * @since 1.13
     */
    protected ListNotasPorProf(java.lang.String matriculaProf) {
      super(Gradeapi.this, "POST", REST_PATH, null, com.appspot.trabalholp.gradeapi.model.NotaCollection.class);
      this.matriculaProf = com.google.api.client.util.Preconditions.checkNotNull(matriculaProf, "Required parameter matriculaProf must be specified.");
    }

    @Override
    public ListNotasPorProf setAlt(java.lang.String alt) {
      return (ListNotasPorProf) super.setAlt(alt);
    }

    @Override
    public ListNotasPorProf setFields(java.lang.String fields) {
      return (ListNotasPorProf) super.setFields(fields);
    }

    @Override
    public ListNotasPorProf setKey(java.lang.String key) {
      return (ListNotasPorProf) super.setKey(key);
    }

    @Override
    public ListNotasPorProf setOauthToken(java.lang.String oauthToken) {
      return (ListNotasPorProf) super.setOauthToken(oauthToken);
    }

    @Override
    public ListNotasPorProf setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListNotasPorProf) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListNotasPorProf setQuotaUser(java.lang.String quotaUser) {
      return (ListNotasPorProf) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListNotasPorProf setUserIp(java.lang.String userIp) {
      return (ListNotasPorProf) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String matriculaProf;

    /**

     */
    public java.lang.String getMatriculaProf() {
      return matriculaProf;
    }

    public ListNotasPorProf setMatriculaProf(java.lang.String matriculaProf) {
      this.matriculaProf = matriculaProf;
      return this;
    }

    @Override
    public ListNotasPorProf set(String parameterName, Object value) {
      return (ListNotasPorProf) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Gradeapi}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Gradeapi}. */
    @Override
    public Gradeapi build() {
      return new Gradeapi(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link GradeapiRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setGradeapiRequestInitializer(
        GradeapiRequestInitializer gradeapiRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(gradeapiRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
